MFD/MFD/Controllers/ArticuloController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MFD.Models;

namespace MFD.Controllers
{
    public class ArticuloController : Controller
    {
        private FitnessContext db = new FitnessContext();

        //
        // GET: /Articulo/

        public ActionResult Index()
        {
            return View(db.Articulos.ToList());
        }

        public ActionResult Articulo()
        {
            return View();
        }

        public ActionResult Calendario()
        {
            return View();
        }

        //
        // GET: /Articulo/Details/5

        public ActionResult Details(int id = 0)
        {
            Articulo articulo = db.Articulos.Find(id);
            if (articulo == null)
            {
                return HttpNotFound();
            }
            return View(articulo);
        }

        //
        // GET: /Articulo/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Articulo/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Articulo articulo)
        {
            if (ModelState.IsValid)
            {
                db.Articulos.Add(articulo);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(articulo);
        }

        //
        // GET: /Articulo/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Articulo articulo = db.Articulos.Find(id);
            if (articulo == null)
            {
                return HttpNotFound();
            }
            return View(articulo);
        }

        //
        // POST: /Articulo/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Articulo articulo)
        {
            if (ModelState.IsValid)
            {
                db.Entry(articulo).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(articulo);
        }

        //
        // GET: /Articulo/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Articulo articulo = db.Articulos.Find(id);
            if (articulo == null)
            {
                return HttpNotFound();
            }
            return View(articulo);
        }

        //
        // POST: /Articulo/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Articulo articulo = db.Articulos.Find(id);
            db.Articulos.Remove(articulo);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

MFD/MFD/Controllers/QueBeberController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MFD.Models;

namespace MFD.Controllers
{
    public class QueBeberController : Controller
    {
        private FitnessContext db = new FitnessContext();

        //
        // GET: /QueBeber/

        public ActionResult Index()
        {
            return View(db.Articulos.ToList());
        }

        //
        // GET: /QueBeber/Details/5

        public ActionResult Details(int id = 0)
        {
            Articulo articulo = db.Articulos.Find(id);
            if (articulo == null)
            {
                return HttpNotFound();
            }
            return View(articulo);
        }

        //
        // GET: /QueBeber/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /QueBeber/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Articulo articulo)
        {
            if (ModelState.IsValid)
            {
                db.Articulos.Add(articulo);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(articulo);
        }

        //
        // GET: /QueBeber/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Articulo articulo = db.Articulos.Find(id);
            if (articulo == null)
            {
                return HttpNotFound();
            }
            return View(articulo);
        }

        //
        // POST: /QueBeber/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Articulo articulo)
        {
            if (ModelState.IsValid)
            {
                db.Entry(articulo).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(articulo);
        }

        //
        // GET: /QueBeber/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Articulo articulo = db.Articulos.Find(id);
            if (articulo == null)
            {
                return HttpNotFound();
            }
            return View(articulo);
        }

        //
        // POST: /QueBeber/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Articulo articulo = db.Articulos.Find(id);
            db.Articulos.Remove(articulo);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

MFD/MFD/Controllers/QueComerController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MFD.Models;

namespace MFD.Controllers
{
    public class QueComerController : Controller
    {
        private FitnessContext db = new FitnessContext();

        //
        // GET: /QueComer/

        public ActionResult Index()
        {
            return View(db.Articulos.ToList());
        }

        //
        // GET: /QueComer/Details/5

        public ActionResult Details(int id = 0)
        {
            Articulo articulo = db.Articulos.Find(id);
            if (articulo == null)
            {
                return HttpNotFound();
            }
            return View(articulo);
        }

        //
        // GET: /QueComer/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /QueComer/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Articulo articulo)
        {
            if (ModelState.IsValid)
            {
                db.Articulos.Add(articulo);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(articulo);
        }

        //
        // GET: /QueComer/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Articulo articulo = db.Articulos.Find(id);
            if (articulo == null)
            {
                return HttpNotFound();
            }
            return View(articulo);
        }

        //
        // POST: /QueComer/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Articulo articulo)
        {
            if (ModelState.IsValid)
            {
                db.Entry(articulo).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(articulo);
        }

        //
        // GET: /QueComer/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Articulo articulo = db.Articulos.Find(id);
            if (articulo == null)
            {
                return HttpNotFound();
            }
            return View(articulo);
        }

        //
        // POST: /QueComer/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Articulo articulo = db.Articulos.Find(id);
            db.Articulos.Remove(articulo);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

MFD/MFD/Controllers/RecetaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MFD.Models;

namespace MFD.Controllers
{
    public class RecetaController : Controller
    {
        private FitnessContext db = new FitnessContext();

        //
        // GET: /Receta/

        public ActionResult Index()
        {
            var recetas = db.Recetas.Include(r => r.Usuario);
            return View(recetas.ToList());
        }

        //
        // GET: /Receta/Details/5

        public ActionResult Details(int id = 0)
        {
            Receta receta = db.Recetas.Find(id);
            if (receta == null)
            {
                return HttpNotFound();
            }
            return View(receta);
        }

        //
        // GET: /Receta/Create

        public ActionResult Create()
        {
            ViewBag.idUsuario = new SelectList(db.Usuarios, "idUsuario", "nick");
            return View();
        }

        //
        // POST: /Receta/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Receta receta)
        {
            if (ModelState.IsValid)
            {
                db.Recetas.Add(receta);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.idUsuario = new SelectList(db.Usuarios, "idUsuario", "nick", receta.idUsuario);
            return View(receta);
        }

        //
        // GET: /Receta/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Receta receta = db.Recetas.Find(id);
            if (receta == null)
            {
                return HttpNotFound();
            }
            ViewBag.idUsuario = new SelectList(db.Usuarios, "idUsuario", "nick", receta.idUsuario);
            return View(receta);
        }

        //
        // POST: /Receta/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Receta receta)
        {
            if (ModelState.IsValid)
            {
                db.Entry(receta).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.idUsuario = new SelectList(db.Usuarios, "idUsuario", "nick", receta.idUsuario);
            return View(receta);
        }

        //
        // GET: /Receta/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Receta receta = db.Recetas.Find(id);
            if (receta == null)
            {
                return HttpNotFound();
            }
            return View(receta);
        }

        //
        // POST: /Receta/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Receta receta = db.Recetas.Find(id);
            db.Recetas.Remove(receta);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

MFD/MFD/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="es">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
        <meta charset="utf-8" />
        <title>Fitness Daw</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/css")
 
     
    </head>
    <body>
        <div id="container">

             <header> 
                                    
                   <nav>
                        <ul id="nav">                       
                            <li>@Html.ActionLink("Inicio", "Index", "Articulo")</li>
                            <li>@Html.ActionLink("Que comer", "Index", "QueComer")</li>
                            <li>@Html.ActionLink("Que beber", "Index", "QueBeber")</li>
                            <li>@Html.ActionLink("Recetas", "Index", "Receta")</li>
                            <li>@Html.ActionLink("Calend. de Dieta", "Calendario", "Articulo")</li>                                                  
                        </ul>
                    </nav>
                 <div class="float-right">
                 <section id="login">
                     @Html.Partial("_LoginPartial")
                 </section>
                 </div>                
             </header>
       
             <div id="body">
                 @RenderSection("featured", required: false)
                 <section class="content-wrapper main-content clear-fix">
                     @RenderBody()
                 </section>
            </div>

            <footer>
                <div class="border"></div>
                <div class="footer-widget">
                    <h4>Some Title</h4>
                    <p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. </p>
                </div>
                <div class="footer-widget">
                    <h4>From The Blog</h4>
                    <ul class="blog">
                        <li><a href="#">Lorem Ipsum Dolor</a><br/>
                            Orciint erdum condimen terdum nulla mcorper elit nam curabitur... </li>
                        <li><a href="#">Praesent Et Eros</a><br/>
                            Orciint erdum condimen terdum nulla mcorper elit nam curabitur... </li>
                        <li><a href="#">Suspendisse In Neque</a><br/>
                            Orciint erdum condimen terdum nulla mcorper elit nam curabitur... </li>
                        <li><a href="#">Suspendisse In Neque</a><br/>
                            Orciint erdum condimen terdum nulla mcorper elit nam curabitur... </li>
                    </ul>
                </div>
                <div class="footer-widget">
                    <h4>We Are Social!</h4>
                    <div id="social"> 
                        <a href="https://twitter.com/FitnessDAW" class="s3d twitter" target="_blank"> Twitter <span class="icons twitter"></span> </a> 
                        <a href="https://www.facebook.com/FitnessDAW?notif_t=fbpage_fan_invite" class="s3d facebook" target="_blank"> Facebook <span class="icons facebook"></span> </a>
                    </div>
                </div>
                <div class="border2"></div>
                <br />
                <span class="copyright">
                    <span class="left"><br />
                        &copy; Copyright @DateTime.Now.Year  - All Rights Reserved - <a href="#">Muñoz Mite Mendoza</a>
                    </span>
                    <span class="right"><br />
                        Espol - <a href="https://www.facebook.com/groups/301410086546520/">Desarrollo de Aplicaciones Web</a><br />
                        <br>
                        <br />
                    </span>
                </span>
            </footer>  
             
        </div>     

        @Scripts.Render("~/bundles/jquery")
        @RenderSection("scripts", required: false)
    </body>
</html>